dist: xenial
language: csharp
solution: Microting.WindowsService.BasePn.sln
mono: none
dotnet: 3.1.101
services:
- mysql
script:
  - dotnet restore
  - dotnet build Microting.WindowsService.BasePn.sln -c Release
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION
  - dotnet pack Microting.WindowsService.BasePn.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/eform-windows-service.BasePn/artifacts/Microting.WindowsService.BasePn.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true
